title: "Talia's GitHub"
description: "MSc Student | WIS"
cover_image: ''

author:
  name: "Talia Baer"
  avatar: "CV_photo_small.jpg"
  bio: "MSc Student | WIS"
  
plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: mint

include:
  - website_text.md
  - README.md # If you want to make sure README.md is processed
