title: "Talia's GitHub"
description: "MSc Student | WIS"

plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: mint

author:
  name   : "Talia Baer"
  avatar : "CV_photo.jpg"
  bio    : "MSc Student | WIS"
  
include:
  - website_text.md
  - README.md # If you want to make sure README.md is processed
